name: Pipeline for EC2 Deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:    
      - name: Deploy to EC2
        uses: action/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH }}
          port: 22
          degub: true
          script: | 
            sudo apt update -y
            sudo apt install nodejs npm -y
            git clone https://github.com/RushiVishwesh/nest-hello-world.git
            cd nest-hello-world
            npm install
            npm start > app.log 2>&1 &
            echo "Application Started"
